// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  BuildCircuitV1CircuitBuildPostData,
  BuildCircuitV1CircuitBuildPostErrors,
  BuildCircuitV1CircuitBuildPostResponses,
  GetBlochVectorV1BlochQubitPostData,
  GetBlochVectorV1BlochQubitPostErrors,
  GetBlochVectorV1BlochQubitPostResponses,
  GetStatevectorV1CircuitStatevectorPostData,
  GetStatevectorV1CircuitStatevectorPostErrors,
  GetStatevectorV1CircuitStatevectorPostResponses,
  ReadRootGetData,
  ReadRootGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Read Root
 *
 * Get API information and available endpoints.
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadRootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  })

/**
 * Build Circuit
 *
 * Build a quantum circuit from gate operations.
 */
export const buildCircuitV1CircuitBuildPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BuildCircuitV1CircuitBuildPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    BuildCircuitV1CircuitBuildPostResponses,
    BuildCircuitV1CircuitBuildPostErrors,
    ThrowOnError
  >({
    url: '/v1/circuit/build',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Statevector
 *
 * Execute circuit and return the statevector.
 */
export const getStatevectorV1CircuitStatevectorPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetStatevectorV1CircuitStatevectorPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GetStatevectorV1CircuitStatevectorPostResponses,
    GetStatevectorV1CircuitStatevectorPostErrors,
    ThrowOnError
  >({
    url: '/v1/circuit/statevector',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Bloch Vector
 *
 * Get Bloch sphere coordinates for a specific qubit.
 */
export const getBlochVectorV1BlochQubitPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBlochVectorV1BlochQubitPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GetBlochVectorV1BlochQubitPostResponses,
    GetBlochVectorV1BlochQubitPostErrors,
    ThrowOnError
  >({
    url: '/v1/bloch/{qubit}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
