// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api` | (string & {})
}

/**
 * BlochVectorResponse
 */
export type BlochVectorResponse = {
  /**
   * X
   */
  x: number
  /**
   * Y
   */
  y: number
  /**
   * Z
   */
  z: number
  /**
   * Qubit
   */
  qubit: number
}

/**
 * CircuitRequest
 */
export type CircuitRequest = {
  /**
   * Num Qubits
   */
  num_qubits: number
  /**
   * Operations
   */
  operations: Array<GateOperation>
}

/**
 * CircuitResponse
 */
export type CircuitResponse = {
  /**
   * Qasm
   */
  qasm: string
  /**
   * Depth
   */
  depth: number
  /**
   * Num Qubits
   */
  num_qubits: number
}

/**
 * GateOperation
 */
export type GateOperation = {
  /**
   * Gate
   */
  gate: string
  /**
   * Qubit
   */
  qubit: number
  /**
   * Params
   */
  params?: Array<number>
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * RootResponse
 */
export type RootResponse = {
  /**
   * Message
   */
  message: string
  /**
   * Api Prefix
   */
  api_prefix: string
  /**
   * Endpoints
   */
  endpoints: Array<string>
}

/**
 * StatevectorResponse
 */
export type StatevectorResponse = {
  /**
   * Amplitudes
   */
  amplitudes: Array<[number, number]>
  /**
   * Probabilities
   */
  probabilities: Array<number>
  /**
   * Basis States
   */
  basis_states: Array<string>
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type ReadRootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type ReadRootGetResponses = {
  /**
   * Successful Response
   */
  200: RootResponse
}

export type ReadRootGetResponse =
  ReadRootGetResponses[keyof ReadRootGetResponses]

export type BuildCircuitV1CircuitBuildPostData = {
  body: CircuitRequest
  path?: never
  query?: never
  url: '/v1/circuit/build'
}

export type BuildCircuitV1CircuitBuildPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type BuildCircuitV1CircuitBuildPostError =
  BuildCircuitV1CircuitBuildPostErrors[keyof BuildCircuitV1CircuitBuildPostErrors]

export type BuildCircuitV1CircuitBuildPostResponses = {
  /**
   * Successful Response
   */
  200: CircuitResponse
}

export type BuildCircuitV1CircuitBuildPostResponse =
  BuildCircuitV1CircuitBuildPostResponses[keyof BuildCircuitV1CircuitBuildPostResponses]

export type GetStatevectorV1CircuitStatevectorPostData = {
  body: CircuitRequest
  path?: never
  query?: never
  url: '/v1/circuit/statevector'
}

export type GetStatevectorV1CircuitStatevectorPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetStatevectorV1CircuitStatevectorPostError =
  GetStatevectorV1CircuitStatevectorPostErrors[keyof GetStatevectorV1CircuitStatevectorPostErrors]

export type GetStatevectorV1CircuitStatevectorPostResponses = {
  /**
   * Successful Response
   */
  200: StatevectorResponse
}

export type GetStatevectorV1CircuitStatevectorPostResponse =
  GetStatevectorV1CircuitStatevectorPostResponses[keyof GetStatevectorV1CircuitStatevectorPostResponses]

export type GetBlochVectorV1BlochQubitPostData = {
  body: CircuitRequest
  path: {
    /**
     * Qubit
     */
    qubit: number
  }
  query?: never
  url: '/v1/bloch/{qubit}'
}

export type GetBlochVectorV1BlochQubitPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetBlochVectorV1BlochQubitPostError =
  GetBlochVectorV1BlochQubitPostErrors[keyof GetBlochVectorV1BlochQubitPostErrors]

export type GetBlochVectorV1BlochQubitPostResponses = {
  /**
   * Successful Response
   */
  200: BlochVectorResponse
}

export type GetBlochVectorV1BlochQubitPostResponse =
  GetBlochVectorV1BlochQubitPostResponses[keyof GetBlochVectorV1BlochQubitPostResponses]
